### ISSUE TITLE
Request: Convert to .NET Core

### ISSUE THREAD

**Issue by aolszowka** [aolszowka/MsBuildProjectReferenceDependencyGraph#18]
Convert this project to .NET Core

The reason is I would like to try and ship these tools as a .NET Core Tool (https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create)

I have been getting pretty good at these conversions and have only had a few "gotchas", in addition I am finding it easiest if I also enable GitHub Actions at the same time (closing #17) to allow for cross-platform unit testing as well as automated NuGet Package creation/distribution. See the latest conversion of VisualStudioSolutionUpdater here: https://github.com/aolszowka/VisualStudioSolutionUpdater/pull/14

Its unclear how many people utilize this in their day to day workflow, but I utilize it pretty heavily myself so it will at least get tested on the Windows side.

@madkat I know you help build the pre-alpha version of this tool initially, but I have no idea if you continued to use it after that, any immediate "don't do this" out of you personally?

**Comment by madkat** [comment]
@aolszowka I have no concerns from a user perspective. .NET Core CLI tools are easily consumable in my workflow.
